exports.STATUS_ACCEPTED = 'ACCEPTED'
exports.STATUS_PENDING = 'PENDING'

exports.UNKNOWN = 'UNKNOWN'
exports.FRIEND = 'FRIEND'
exports.ME = 'ME'
exports.REQUESTER = 'REQUESTER'
exports.RECEIVER = 'RECEIVER'